#!/bin/bash

if tput setaf 1 &> /dev/null; then
    tput sgr0; # reset colors
    reset=$(tput sgr0);
    # Solarized colors, taken from http://git.io/solarized-colors.
    blue=$(tput setaf 33);
    cyan=$(tput setaf 37);
    green=$(tput setaf 64);
    orange=$(tput setaf 166);
    red=$(tput setaf 124);
    white=$(tput setaf 15);
    yellow=$(tput setaf 136);
else
    reset="\e[0m";
    blue="\e[1;34m";
    cyan="\e[1;36m";
    green="\e[1;32m";
    orange="\e[1;33m";
    red="\e[1;31m";
    white="\e[1;37m";
    yellow="\e[1;33m";
fi;

PS1='\[${orange}\]\u\[${reset}\]'
PS1+='\[${white}\]@\[${reset}\]'
PS1+='\[${yellow}\]\h\[${reset}\]'
if [ -f /.dockerenv ]; then
  # Unicode Moby
  PS1+=' 🐳  '
fi
PS1+='\[${white}\]:\[${reset}\]'
PS1+='\[${green}\]\W\[${reset}\]'
PS1+='\[${white}\]:\[${reset}\]'
PS1+='$(kube_ps1)\$ '
export PS1

PS2="\[${yellow}\]→ \[${reset}\]"
export PS2
