#!/bin/bash

# Moby icon when in containers
MOBY=$'\U1F433'

if tput setaf 1 &> /dev/null; then
    tput sgr0; # reset colors
    reset=$(tput sgr0)
    # Solarized colors, taken from http://git.io/solarized-colors.
    green=$(tput setaf 64)
    orange=$(tput setaf 166)
    # red=$(tput setaf 124)
    white=$(tput setaf 15)
    yellow=$(tput setaf 136)
else
    reset='\e[0m'
    green='\e[1;32m'
    orange='\e[1;33m'
    red='\e[1;31m'
    white='\e[1;37m'
    yellow='\e[1;33m'
fi

# Highlight the user name when logged in as root.
if [[ "${USER}" == "root" ]]; then
	userStyle="${red}"
else
	userStyle="${orange}"
fi

PS1='\[${userStyle}\]\u\[${reset}\]'
PS1+='\[${white}\]@\[${reset}\]'
PS1+='\[${yellow}\]\h\[${reset}\]'
if [ -f /.dockerenv ]; then
  # Unicode Moby
  PS1+=' \[${MOBY}\] '
fi
PS1+='\[${white}\]:\[${reset}\]'
PS1+='\[${green}\]\W\[${reset}\]'
PS1+='\[${white}\]:\[${reset}\]'
PS1+='$(kube_ps1)\$\[${reset}\] '
export PS1

PS2='\[${yellow}\]→ \[${reset}\]'
export PS2
