#!/bin/bash

# Moby icon when in containers
MOBY=$'\U1F433 '

if tput setaf 1 &> /dev/null; then
    tput sgr0; # reset colors
    reset=$(tput sgr 0)
    # Solarized colors, taken from http://git.io/solarized-colors.
    green=$(tput setaf 64)
    orange=$(tput setaf 166)
    # red=$(tput setaf 124)
    white=$(tput setaf 15)
    yellow=$(tput setaf 136)
else
    reset='\e[0m'
    green='\e[1;32m'
    orange='\e[1;33m'
    red='\e[1;31m'
    white='\e[1;37m'
    yellow='\e[1;33m'
fi

# Highlight the user name when logged in as root.
if [[ "${USER}" == "root" ]]; then
	userStyle="${red}"
else
	userStyle="${orange}"
fi

PS1='\[${userStyle}\]\u\[${reset}\]'
PS1+='\[${white}\]@\[${reset}\]'
PS1+='\[${yellow}\]\h\[${reset}\]'

if [ -f /.dockerenv ]; then
  # Unicode Moby
  PS1+=' \[${MOBY}\] '
fi

PS1+='\[${white}\] in \[${reset}\]'
PS1+='\[${green}\]\w \[${reset}\]'

# stable release directory
if [[ -f "${HOME}/projects/kube-ps1/github/kube-ps1/kube-ps1.sh" ]]; then
  PS1+='$(kube_ps1) \[${reset}\]'
  source "${HOME}/projects/kube-ps1/github/kube-ps1/kube-ps1.sh"
fi

PS1+="\\n"
PS1+='\$ \[${reset}\]'
export PS1

PS2='\[${yellow}\]→ \[${reset}\]'
export PS2

# export KUBECONFIG=$HOME/.kube/config:$HOME/.kube/k3s-config:$HOME/.kube/rke2-config
export KUBE_PS1_SYMBOL_PADDING=false

# git prompt
if [ -f "$HOME/repos/bash-git-prompt/gitprompt.sh" ]; then
    GIT_PROMPT_ONLY_IN_REPO=1
    GIT_PROMPT_THEME=Solarized
    source $HOME/repos/bash-git-prompt/gitprompt.sh
fi
