#!/bin/bash
#
# function helpers for docker commands

# Set our registry based on location
function registry_fp() {
  export REGISTRY=registry.forkedprocess.com
  docker login -u jmosco registry.forkedprocess.com
}

function registry_csc() {
  export REGISTRY=docker-dev-local.cscinfo.com
  docker login -u jmosco docker-dev-local.cscinfo.com
}

# Get a containers PID
function container_pid() {
  docker inspect --format '{{ .State.Pid }}' "$1"
}

# Clean up images that are tagged <none>:<none>
# dangling images and needs to be pruned
function clean_dangling() {
  docker rmi "$(docker images -f "dangling=true" -q)"
}

# Create our utility container
# check if the image is local and exists, otherwise
# build it then run the container
function utility() {
  if ! docker run --name=utility --rm -it ${REGISTRY}/jmosco-utility:1.0 /bin/bash; then
    docker cp "$HOME/.ssh/id_rsa.pub" utility:/home/jmosco/.ssh/id_rsa.pub
    docker exec -ti utility sudo chown jmosco: /home/jmosco/.ssh/id_rsa.pub
  fi
}

function utility_ssh() {
  docker cp "$HOME/.ssh/id_rsa.pub" utility:/home/jmosco/.ssh/id_rsa.pub
  docker exec -ti utility sudo chown jmosco: /home/jmosco/.ssh/id_rsa.pub
}

function dclean() {
  local containers
  containers=( $(docker ps -aq 2>/dev/null) )
  docker rm "${containers[@]}" 2>/dev/null
}
