#!/bin/bash

export HISTCONTROL=ignoreboth
export HISTFILESIZE=150000
export HISTSIZE=150000
export HISTTIMEFORMAT="%D %I:%M "
export PAGER=less
export GREP_COLORS='1;37;41'
export MAIL=$HOME/.mail
export XAUTHORITY=~/.Xauthority
