#!/bin/bash

# Restore default prompt
function prompt_default () {
  source ~/.zsh/prompt/steeef.zsh-theme
}

# kubectl context
function prompt_k8s () {
PROMPT=$'
%F{166}%n${PR_RST} $fg[white]%}at${PR_RST} %{$orange%}%m${PR_RST} $fg[white]%}in${PR_RST} %{$limegreen%}%~${PR_RST} $(git_super_status)$(virtualenv_info)(%F{blue}k8s:%f%F{161}$(kubectl config view --minify  --output 'jsonpath={..namespace}')%f)
$ '
}

# Switch to a simple prompt to aid in pasting
function prompt_paste () {
  export PROMPT='$ '
}


# Flush DNS cache
# sometimes after being on VPN, DNS gets a little strange
function flush_dns() {
  sudo killall -HUP mDNSResponder;sudo killall mDNSResponderHelper;sudo dscacheutil -flushcache
}

