#!/bin/bash

# Restore default prompt
function prompt_default () {
  # shellcheck disable=SC1090
  source ~/.zsh/prompt/steeef.zsh-theme
}

# kubectl context
function prompt_k8s () {
  # shellcheck disable=SC1090
  source ~/repos/kube-ps1/kube-ps1.sh
  # shellcheck disable=SC2125
  PROMPT=$'
%F{166}%n${PR_RST} $fg[white]%}at${PR_RST} %{$orange%}%m${PR_RST} $fg[white]%}in${PR_RST} %{$limegreen%}%~${PR_RST} $(git_super_status)$(virtualenv_info)$(kube_ps1)
$ '
}

# Switch to a simple prompt to aid in pasting
function prompt_paste () {
  export PROMPT='$ '
}

function prompt_simple () {
  # Robby Russel prompt to use for minimal prompt
  ret_status="%(?:%F{166%}➜${PR_RST} :%{$fg_no_bold[red]%}➜${PR_RST} )"
  # shellcheck disable=SC2016
  PROMPT='${ret_status} %{$fg[cyan]%}%c%{$reset_color%}${PR_RST} $(git_super_status) '
}

function prompt_simple_k8s () {
  # shellcheck disable=SC1090
  source ~/repos/kube-ps1/kube-ps1.sh
  ret_status="%(?:%F{166}➜ :%{$fg_no_bold[red]%}➜ )"
  # shellcheck disable=SC2016
  PROMPT='${ret_status} %{$fg[cyan]%}%c%{$reset_color%}${PR_RST} $(git_super_status) $(kube_ps1) '
}

function prompt_bash_k8s () {
  orange=$(tput setaf 166);
  green=$(tput setaf 64);

  # shellcheck disable=SC1090
  source ~/repos/kube-ps1/kube-ps1.sh
  PS1="\[${orange}\]\u\[\e[1;37m\]@\[\e[0;33m\]\h\[\e[0;38m\]\e[1;37m\]:\[${green}\]\w\[\e[0;38m\]\e[1;37m\]:\[\e[0;38m\]$(kube_ps1)$ "
  export PS1
}

# Flush DNS cache
# sometimes after being on VPN, DNS gets a little strange
function flush_dns() {
  sudo killall -HUP mDNSResponder;sudo killall mDNSResponderHelper;sudo dscacheutil -flushcache
}
