#!/bin/bash

# Go
export GOPATH="${HOME}/code/go"

# add Go to path
export PATH="/usr/local/go/bin:${GOPATH}/bin:${PATH}"

# Krew
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# pip
export PATH="${HOME}/.local/bin:${PATH}"

# linkerd
export PATH=$PATH:/home/jmosco/.linkerd2/bin

# kubectl KUBECONFIG files
# export KUBECONFIG=$HOME/.kube/config:$HOME/.kube/k3s-config:$HOME/.kube/rke2-config
export KUBECONFIG=$HOME/.kube/rke2-config:$HOME/.kube/k3s-config:$HOME/.kube/config
# export KUBECONFIG=$HOME/.kube/config:$HOME/.kube/rke2-config:$HOME/.kube/k3s-config
