pragma Singleton

import Quickshell
import Quickshell.Io
import Quickshell.Hyprland
import QtQuick

Singleton {
  id: root

  property var  monitors:             []
  property bool loading:              false
  property bool persistenceAvailable: false

  property var  _lastEdits:     []
  property bool _pendingVerify: false

  signal monitorsLoaded()
  signal applyDone(bool hasErrors, string errorText)

  function findCurrentMode(m) {
    const target      = `${m.width}x${m.height}`;
    const rateRounded = Math.round(m.refreshRate);
    return m.availableModes.find(mode => {
      const match = mode.match(/^(\d+x\d+)@([\d.]+)Hz$/);
      return match
        && match[1] === target
        && Math.round(parseFloat(match[2])) === rateRounded;
    }) ?? m.availableModes[0]
      ?? `${m.width}x${m.height}@${m.refreshRate.toFixed(2)}Hz`;
  }

  // Shared core: builds one monitor line with a caller-supplied prefix
  // ("keyword monitor " for hyprctl, "monitor=" for monitors.conf)
  function buildMonitorLine(m, prefix) {
    if (m.disabled) return `${prefix}${m.name},disable`;
    const parsed = MonitorUtils.parseMode(m.selectedMode);
    const res  = parsed ? `${parsed.w}x${parsed.h}` : `${m.width}x${m.height}`;
    const rate = parsed ? parsed.rate : m.refreshRate.toFixed(2);
    let line = `${prefix}${m.name},${res}@${rate},${m.x}x${m.y},${m.scale}`;
    if (m.transform !== 0) line += `,transform,${m.transform}`;
    if (m.mirrorOf  !== "") line += `,mirror,${m.mirrorOf}`;
    return line;
  }

  function buildMonitorArg(m) {
    return buildMonitorLine(m, "keyword monitor ");
  }

  function buildFileContent(edits) {
    const lines = ["# Generated by Quickshell MonitorManager"];
    for (const m of edits) lines.push(buildMonitorLine(m, "monitor="));
    return lines.join("\n") + "\n";
  }

  function refresh() {
    refreshDebounce.restart();
  }

  function _doRefresh() {
    if (loading) return;
    loading = true;
    queryProc.running = true;
  }

  function apply(edits) {
    // Guard against double-apply
    if (applyProc.running) return;
    _lastEdits = edits;
    const parts = edits.map(buildMonitorArg);
    applyProc.command = ["hyprctl", "--batch", parts.join(" ; ")];
    applyProc.running = true;
  }

  function persistToFile(edits) {
    const content = buildFileContent(edits);
    writeProc.command = [
      "python3", "-c",
      `import os; open(os.path.expanduser('~/.config/hypr/monitors.conf'), 'w').write(${JSON.stringify(content)})`
    ];
    writeProc.running = true;
  }

  function verifyApply() {
    const mismatches = [];
    for (const edit of _lastEdits) {
      const live = monitors.find(m => m.name === edit.name);
      if (!live) {
        mismatches.push(`${edit.name}: not found after apply`);
        continue;
      }
      if (live.disabled !== edit.disabled)
        mismatches.push(`${edit.name}: enabled state did not apply`);
      if (!edit.disabled && live.selectedMode !== edit.selectedMode)
        mismatches.push(`${edit.name}: mode ${edit.selectedMode} → got ${live.selectedMode}`);
    }
    _pendingVerify = false;
    applyDone(mismatches.length > 0, mismatches.join("; "));
  }

  onMonitorsLoaded: {
    if (_pendingVerify) verifyApply();
  }

  // Debounce timer — absorbs hotplug bursts (DisplayPort negotiation)
  Timer {
    id: refreshDebounce
    interval: 250
    repeat: false
    onTriggered: root._doRefresh()
  }

  // Check persistence availability on startup
  Process {
    id: sourceCheck
    command: ["sh", "-c",
      "grep -q 'source.*monitors\\.conf' \"$HOME/.config/hypr/hyprland.conf\" && echo yes || echo no"]
    running: true
    stdout: StdioCollector {
      onStreamFinished: {
        root.persistenceAvailable = text.trim() === "yes";
      }
    }
    stderr: StdioCollector {
      onStreamFinished: {
        if (text.trim() !== "") console.warn("MonitorService sourceCheck:", text.trim());
      }
    }
  }

  // Query live monitor state
  Process {
    id: queryProc
    command: ["hyprctl", "-j", "monitors", "all"]
    running: false
    stdout: StdioCollector {
      onStreamFinished: {
        try {
          const raw = JSON.parse(text);
          root.monitors = raw.map(m => ({
            name:           m.name,
            description:    m.description,
            width:          m.width,
            height:         m.height,
            x:              m.x,
            y:              m.y,
            selectedMode:   root.findCurrentMode(m),
            scale:          m.scale,
            transform:      m.transform,
            disabled:       m.disabled,
            mirrorOf:       (() => {
              if (!m.mirrorOf || m.mirrorOf === "none") return "";
              // hyprctl -j returns mirrorOf as a stringified monitor ID (e.g. "0") rather than
              // the monitor name, so a direct display in the UI would show "0" instead of
              // "eDP-1".  Resolve it to the name so the rest of the codebase never sees raw IDs.
              const asId = parseInt(m.mirrorOf, 10);
              if (!isNaN(asId)) return raw.find(x => x.id === asId)?.name ?? "";
              return m.mirrorOf;
            })(),
            availableModes: m.availableModes,
          }));
          root.loading = false;
          root.monitorsLoaded();
        } catch (e) {
          console.error("MonitorService: JSON parse failed:", e);
          root.loading = false;
        }
      }
    }
    stderr: StdioCollector {
      onStreamFinished: {
        if (text.trim() !== "") console.warn("MonitorService queryProc:", text.trim());
      }
    }
  }

  // Apply monitor configuration
  Process {
    id: applyProc
    running: false
    stdout: StdioCollector {
      onStreamFinished: {
        // hyprctl always exits 0 — parse stdout for errors
        const lines  = text.trim().split("\n");
        const errors = lines.filter(l => l.trim() !== "" && l.trim() !== "ok");

        if (errors.length > 0) {
          root.applyDone(true, errors.join("; "));
        } else {
          root._pendingVerify = true;
          root.loading = true;
          // If queryProc is already running (poll timer race), it will finish
          // and call monitorsLoaded → verifyApply via _pendingVerify.
          // If it's idle, start it now.
          if (!queryProc.running) queryProc.running = true;
        }
      }
    }
    stderr: StdioCollector {
      onStreamFinished: {
        if (text.trim() !== "") {
          root.applyDone(true, text.trim());
        }
      }
    }
  }

  // Write monitors.conf — fire and forget; log errors
  Process {
    id: writeProc
    running: false
    stdout: StdioCollector {}
    stderr: StdioCollector {
      onStreamFinished: {
        if (text.trim() !== "")
          console.error("MonitorService: monitors.conf write failed:", text.trim());
      }
    }
  }

  // Listen for Hyprland events: hotplug and config reload
  Connections {
    target: Hyprland
    function onRawEvent(event) {
      // Never interrupt post-apply verification for config reload,
      // but allow hotplug events through so newly connected monitors
      // are detected even if we're mid-verify
      if (root._pendingVerify && event.name === "configreloaded") return;

      const triggers = ["monitoradded", "monitorremoved", "configreloaded"];
      if (triggers.includes(event.name)) root.refresh();
    }
  }
}
