# Dracula - tmux theme (official palette)

set -g window-status-style fg=#6272a4,bg=#282a36,none
set -g message-command-style fg=#f8f8f2,bg=#44475a
set -g status-style bg=#282a36,none
set -g message-style fg=#f8f8f2,bg=#44475a
set -g status-right-style none
set -g status-left-style none
set -g status-left-length 40
set -g status-right-length 120

set -g mode-style fg=#282a36,bg=#bd93f9
set -g pane-border-style fg=#44475a,bg=default
set -g pane-active-border-style fg=#bd93f9,bg=default

setw -g window-status-format " #I #W "

setw -g window-status-current-format "\
#{?window_zoomed_flag, ,}\
#[fg=#282a36,bg=#bd93f9,nobold,nounderscore,noitalics]\
#[fg=#282a36,bg=#bd93f9,bold] #I ❯ #W \
#[fg=#bd93f9,bg=#282a36,nobold,nounderscore,noitalics]"

set -g status-left "\
#{?client_prefix,#[fg=#282a36 bg=#f1fa8c bold]  #S #[fg=#f1fa8c bg=#282a36 nobold nounderscore noitalics],\
#[fg=#282a36 bg=#50fa7b bold]  #S #[fg=#50fa7b bg=#282a36 nobold nounderscore noitalics]}"

set -g status-right "\
#[fg=#44475a,bg=#282a36]#[fg=#f8f8f2,bg=#44475a] \
#(/bin/bash ~/projects/kube-tmux/kube-tmux/kube.tmux 250 red cyan) \
#(/bin/bash ~/.config/tmux/battery.sh colour59) #[fg=#bd93f9,bg=#44475a]\
#[fg=#282a36,bg=#bd93f9,bold]  %D  %l:%M %p \
#[fg=#ffb86c,bg=#bd93f9,nobold,nounderscore,noitalics]\
#[fg=#282a36,bg=#ffb86c,bold]  #h #[fg=#ffb86c,bg=#282a36,nobold,nounderscore,noitalics]"
