general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Dim screen as a warning before locking
listener {
    timeout = 1770
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# Lock after 30 minutes
listener {
    timeout = 1800
    on-timeout = loginctl lock-session
}

# Turn off screen 30 seconds after locking
listener {
    timeout = 1830
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
